Staging -> Production
indigenousfriends/itlct-website-development pull request #46
Opened 2024-02-02 19:40 UTC by maxharrisnet

**Changes**

- Adding CMS to all pages with `pages.js`
- Pulling Team Members from the CMS in `team.js`
-- Constructing cards and modals for team

**Testing**
- Current state can be seen in staging: https://staging.iftheselandscouldtalk.org/
- WordPress CMS Admin: https://wp.iftheselandscouldtalk.org/wp-admin
- Edit content in WordPress, view changes on corresponding pages/sections. All page content should be editable.
- Admin > Pages to pages
- Admin > Events (this is currently working in production, so be careful with publishing)

2024-02-02 19:50 UTC, maxharrisnet commented on js/main.js
> -
Moving all of this to `team.js`

2024-02-02 19:51 UTC, maxharrisnet commented on js/main.js
> -		let member = button.dataset.content;
Moving the member stuff to `team.js`

2024-02-02 19:54 UTC, maxharrisnet commented on js/main.js
> +// Helper functions for appending data to DOM elements
This is meant to keep all the appending as DRY as possible and to run checks. The function works but could probably be improved (moving quickly).

2024-02-02 19:56 UTC, maxharrisnet commented on js/pages.js
> +			const data = response[0].acf;
Advanced Custom Fields is the WordPress plugin that is used to create the fields. All of the data we need is coming is from that object (except the title).

2024-02-02 20:05 UTC, maxharrisnet commented on js/pages.js
> +// Fetch page data from WordPress
This file is for all pages. It fetches the data for that page. If new data exists from the CMS, we append it to some element with `appendData()` in `main.js`.

Using IDs to target most things.
Data from the CMS is set  up to use the same fields on each page (i.e. `section_1`, `hero_image`) and the pages use the same IDs (i.e. `#section-1`, `#hero-image`).

2024-02-02 20:06 UTC, maxharrisnet commented on js/pages.js
> +			// Main Content Sections
This is used on about half of the pages - those with a big single area for content like About Us.

2024-02-02 20:07 UTC, maxharrisnet commented on js/pages.js
> +			// Generic Content Sections
These are the mostly 2-column sections on many pages (Homepage, Impact, etc.)

2024-02-02 20:08 UTC, maxharrisnet commented on js/pages.js
> +						// appendData(sectionData.button, "button", "link", sectionButton);
Not working, appends the wrong way.

2024-02-02 20:10 UTC, maxharrisnet commented on js/team.js
> +// Populate modal
This file fetches all of the team members from the CMS, generates card components for each, and generates modal data for each.

2024-02-02 20:11 UTC, maxharrisnet commented on js/team.js
> +function populateTeamModal(data) {
Making the modal data dynamic

2024-02-02 20:12 UTC, maxharrisnet commented on js/team.js
> +function generateCards(items) {
Creating card components to append to the container. 

<img width="1501" alt="Screen Shot 2024-02-02 at 12 21 28 PM" src="https://github.com/indigenousfriends/itlct-website-development/assets/704697/631a97ea-0060-4be2-961e-21f40b6bb913">

2024-02-02 20:13 UTC, maxharrisnet commented on js/team.js
> +			btn.addEventListener("click", () => {
Event listener for populating and opening modals.

2024-02-02 20:15 UTC, maxharrisnet commented on js/team.js
> +function getAllTeamData() {
🐶

2024-02-02 20:15 UTC, maxharrisnet commented on team.html
> -				<ul class="team-members">
Replacing static content with dynamic

2024-02-02 20:16 UTC, maxharrisnet commented on js/cms.js
This was broken up into the other JS files

2024-02-02 20:18 UTC, maxharrisnet commented on js/pages.js
> +			// Cards
2 and 3 column card elements (Values page)
<img width="1463" alt="Screen Shot 2024-02-02 at 12 17 56 PM" src="https://github.com/indigenousfriends/itlct-website-development/assets/704697/742177ab-e9b8-439b-a770-a8444fa80afa">

2024-02-02 20:19 UTC, maxharrisnet commented on js/pages.js
> +			// Hero
Hero

<img width="1382" alt="Screen Shot 2024-02-02 at 12 18 30 PM" src="https://github.com/indigenousfriends/itlct-website-development/assets/704697/1b516fa5-6a70-48a2-ad10-6d3141f01e46">

2024-02-02 20:19 UTC, maxharrisnet commented on js/pages.js
> +			// Main Content Sections
<img width="1523" alt="Screen Shot 2024-02-02 at 12 19 15 PM" src="https://github.com/indigenousfriends/itlct-website-development/assets/704697/a0e7f119-6734-4390-bff1-267eced546dc">

2024-02-06 20:30 UTC, isaackIFA requested changes
Looks good! WordPress CMS creation, editing and deleting are all working for pages, events and team members. All changes show up on website without any issues.

There are a 2 small UI issues on the "Our Team" page
- Duplicate sentence under "Our Current Positions" Section<img width="960" alt="Screenshot 2024-02-06 at 10 50 53 AM" src="https://github.com/indigenousfriends/itlct-website-development/assets/135652071/b9555425-a146-4404-ab3d-f1af1831ddb8">

- Homepage button links to default/blank wordpress page<img width="960" alt="Screenshot 2024-02-06 at 11 08 17 AM" src="https://github.com/indigenousfriends/itlct-website-development/assets/135652071/eec69826-d66a-483f-92a4-af2cb1411e86">

2024-02-08 19:52 UTC, merged